ORG 00H
MOV A, 30H ; READ THE NUMBER FROM INTERNAL MEMORY
ANL A, #0FH ; SEPERATING LOWER NIBBLE
ADD A, #30H ; TO ASCII
MOV 51H, A ; SAVE LOWER NIBBLE
MOV A, 30H ;RESTORE THE NUMBER
ANL A, #0F0H ;SEPERATING UPPER NIBBLE
SWAP A ;SWAP UPPER NIBBLE TO LOWER NIBBLE
ADD A, #30H ;TO ASCII
MOV 50H, A ;UPPER NIBBLE
END